### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by Shanlans** [MathiasGruber/SRGAN-Keras#1]
May you release your pretrain model for this repo?

**Comment by PraveenAsh** [comment]
Yes! With such a deep network, it would take a very long time to train with average GPU. So please provide the pre-trained model.

**Comment by aezco** [comment]
@Shanlans @PraveenAsh  Do one of you have a trained model?

**Comment by Shanlans** [comment]
> @Shanlans @PraveenAsh Do one of you have a trained model?

Sorry, haven't yet. Already focused on the other implementation.

**Comment by PraveenAsh** [comment]
If it helps, SRGAN implemented by [Klassen](https://github.com/krasserm/super-resolution) has weights and it can be easily retained if need. I found the current weights itself interesting.

**Comment by aezco** [comment]
@PraveenAsh

Is it trainable on human faces without smoothing?
